id = "macos-classic"
name = "macOS Classic Theme"
description = "A macOS native style theme, let it same like native app in macOS."
version = "0.2.2"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/huacnlee/zed-theme-macos-classic"
